// Case study + resume data pulled from the Figma source
const CASES = [
  {
    id: 'hibob',
    company: 'HiBob',
    title: 'Payroll admin experience',
    dates: 'JUN 2025 — PRESENT',
    tags: 'PRODUCT STRATEGY, DESIGN & RESEARCH',
    role: 'Senior Product Designer',
    summary: 'Leading design initiatives to establish scalable and intuitive features that empower payroll admins to proactively manage and accurately process payroll on-time. Focused on reducing friction and redundancy across key operational workflows.',
    artStyle: 'logo',
    accent: '#E6F0FF',
    link: true,
  },
  {
    id: 'shopify',
    company: 'Shopify',
    title: 'Purchase order strategy',
    dates: 'NOV 2024 — APR 2025',
    tags: 'PRODUCT STRATEGY, DESIGN & USER RESEARCH',
    role: 'Senior Product Designer',
    summary: 'Led green-path design initiatives to optimize Shopify\u2019s inventory management systems, with a focus on streamlining the purchase order experience. Conducted user research with merchants to identify pain points and prioritize design initiatives.',
    artStyle: 'shopify',
    accent: '#E0F1E8',
    link: true,
  },
  {
    id: 'leaflink',
    company: 'LeafLink',
    title: 'Compliance integration hub',
    dates: 'MAR 2022 — APR 2024',
    tags: 'PRODUCT STRATEGY, DESIGN & USER RESEARCH',
    role: 'Staff Product Designer',
    summary: 'Designed an integrations platform connecting wholesalers to state-mandated compliance systems (Metrc, BioTrack). Led research to identify pain points in manual reconciliation workflows, then shipped a hub that automated traceability reporting for 1,200+ licensees.',
    artStyle: 'leaflink',
    accent: '#F7FCBC',
    link: true,
  },
  {
    id: 'traceability',
    company: 'LeafLink × Metrc',
    title: 'Traceability case study',
    dates: 'OCT 2021 — FEB 2022',
    tags: 'PRODUCT DESIGN, UXR',
    role: 'Staff Product Designer',
    summary: 'Designed the reconciliation flow between LeafLink\u2019s order system and Metrc\u2019s state-mandated seed-to-sale tracking. Translated dense regulatory requirements into a workflow that operators could complete in under three minutes instead of thirty.',
    artStyle: 'llmetrc',
    accent: '#F7FCBC',
    link: true,
  },
  {
    id: 'prodcreation',
    company: 'LeafLink',
    title: 'Product creation re-architecture',
    dates: 'NOV 2022 — APR 2024',
    tags: 'PRODUCT STRATEGY, DESIGN & USER RESEARCH',
    role: 'Staff Product Designer',
    summary: 'Re-architected how sellers create and manage SKUs across a fragmented inventory system. Worked with engineering to collapse three legacy flows into a single modal-based experience, reducing support tickets by 42%.',
    artStyle: 'prodcreation',
    accent: '#CCE3FC',
    link: true,
    hidden: true,
  },
  {
    id: 'amex',
    company: 'American Express',
    title: 'Card application standardization',
    dates: 'AUG 2020 — SEP 2021',
    tags: 'PRODUCT DESIGN, UXR',
    role: 'Senior Product Designer',
    summary: 'Strategized with product to enhance and standardize the card application process across international markets. Collaborated with UXR team to advocate for enhancing the consumer experience while satisfying risk & compliance requirements.',
    artStyle: 'amex',
    accent: '#FFFFFF',
    link: false,
    hidden: true,
  },
  {
    id: 'banconext',
    company: 'Banco Next (Capco)',
    title: 'Onboarding redesign',
    dates: 'JUL — SEP 2018',
    tags: 'PRODUCT DESIGN & STRATEGY • USER RESEARCH • PROTOTYPING',
    role: 'Product Designer (Consulting)',
    summary: 'Redesigned the digital banking onboarding flow for Brazil\u2019s Banco Next. Conducted generative research with new-to-banking customers, prototyped a conversational welcome flow, and tested it through four rounds of moderated usability sessions.',
    artStyle: 'banco',
    accent: '#CCE3FC',
    link: true,
  },
  {
    id: 'redantler',
    company: 'Red Antler',
    title: 'Brand-led commerce experiences',
    dates: 'MAR 2019 — JUN 2020',
    tags: 'UX STRATEGY, E-COMMERCE',
    role: 'Senior Product Designer',
    summary: 'Created and pitched UX strategies for startup Direct-to-Consumer and service brands. Primarily focused on leveraging strategic brand work to create engaging e-commerce experiences. Clients: MyVillage, Oova, Bonafide, Henry Rose, Kaleidoscope.',
    artStyle: 'redantler',
    accent: '#FFFFFF',
    link: false,
    hidden: true,
  },
];

const RESUME = {
  name: 'Justina Eng',
  bio: 'UX professional with 10+ years of experience spanning various complex industries. I leverage my UXR skills to hone in on problem definition and to evaluate design solutions.',
  contact: {
    email: 'justina.eng@gmail.com',
    phone: '908-883-0746',
    site: 'portfolio.justina.design',
    location: 'Brooklyn, NY',
  },
  experience: [
    { company: 'HiBob', role: 'Senior Product Designer', dates: 'Jun 2025 — Current', blurb: 'Leading design initiatives to establish scalable and intuitive features that empower payroll admins to proactively manage and accurately process payroll on-time.' },
    { company: 'Shopify', role: 'Senior Product Designer', dates: 'Oct 2024 — Apr 2025', blurb: 'Led green-path design initiatives to optimize Shopify\u2019s inventory management systems, with a focus on streamlining the purchase order experience.' },
    { company: 'LeafLink', role: 'Staff Product Designer', dates: 'Oct 2021 — Apr 2024', blurb: 'Crafted design solutions for supply chain workflows: transportation, inventory management, fulfillment, and compliance. Led and operated all UXR functions for the Design team.' },
    { company: 'American Express', role: 'Senior Product Designer', dates: 'Aug 2020 — Sep 2021', blurb: 'Strategized with product to enhance and standardize the card application process across international markets.' },
    { company: 'Red Antler', role: 'Senior Product Designer', dates: 'Mar 2019 — Jun 2020', blurb: 'Created and pitched UX strategies for startup DTC and service brands. Clients: MyVillage, Oova, Bonafide, Henry Rose, Kaleidoscope.' },
  ],
  skills: {
    design: 'Figma, Sketch, Principle, Framer',
    research: 'User interviews · Contextual inquiry · Usability study · Survey design · SUS & SEQ · A/B testing',
  },
  education: {
    school: 'Carnegie Mellon University',
    degree: 'B.S. Technical Writing',
    minor: 'Minor in Human-Computer Interaction & Fine Arts',
  },
  ooo: 'Snowboarding · Alpine touring (splitboarding) · Tennis · Hiking / Running · Mountain biking · Amateur dog agility',
};

Object.assign(window, { CASES, RESUME });
